networks:
  app:
    driver: bridge

services:
  backend:
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
      context: backend
    restart: always
    hostname: backend
    networks:
      - app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./backend/data/root.crt:/home/jboss/.postgresql/root.crt

  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
    restart: always
    hostname: frontend
    networks:
      - app
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - backend
